### ISSUE TITLE
Minor updates to GTFS site Dec 2022

### ISSUE THREAD

**Issue by mrose914** [cal-itp/gtfs.calitp.org#17]
- San Joaquin Dial a Ride url needs to be updated from SanJoaquinRTFFialARide to DialARide (just fixing the F in the url to a D)
- Humboldt Transit Authority needs to have Flex added to the end of the url so it's https://gtfs.calitp.org/production/HumboldtTransitAuthorityDialARideFlex.zip

**Comment by thekaveman** [comment]
Hi @mrose914 -- I'll make these changes today or tomorrow. Also, I migrated this issue from the calitp.org repo.

**Comment by thekaveman** [comment]
@mrose914 heads up - for San Joaquin, the file name needs a further edit, it should be [`SanJoaquinRTD`](https://sanjoaquinrtd.com/) not `SanJoaquinRTF`. 

I'm going to make that edit as part of these changes, just wanted you to know.
